[package]
name = "csx64"
version = "0.1.0"
authors = ["dragazo <37459229+dragazo@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
bitflags = "1.2.1"
bytemuck = "1.4.1"
rug = "1.11.0"
memchr = "2.3.3"
num-traits = "0.2.12"
num-derive = "0.3.2"
getrandom = "0.2.0"
rand_core = "0.5.1"
rand_xorshift = "0.2.0"